# permissions for end users to edit osartifacts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osartifact-editor-role
rules:
- apiGroups:
  - build.kairos.io
  resources:
  - osartifacts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - build.kairos.io
  resources:
  - osartifacts/status
  verbs:
  - get
