# permissions for end users to view osartifacts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osartifact-viewer-role
rules:
- apiGroups:
  - build.kairos.io
  resources:
  - osartifacts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - build.kairos.io
  resources:
  - osartifacts/status
  verbs:
  - get
