---
name: 'test'

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
          make kind-e2e-tests